package org.util.exception;

public class ExceptionMain {

	public static void main(String[] args)throws Exception {
							
		System.out.println("메인 시작");
		
		Test test =new Test();
		
		test.t2();
		
		System.out.println("메인 종료");
		
		
	}

}
